// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaPc.DLL.Models;

public partial class CategoriaFiscal
{
    public int IdCategoriaFiscal { get; set; }

    public string NombreCategoriaFiscal { get; set; }

    public virtual ICollection<Pedido> Pedidos { get; set; } = new List<Pedido>();
}