// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaPc.DLL.Models;

public partial class Componente
{
    public int IdComponente { get; set; }

    public int IdMarca { get; set; }

    public int IdTipoComponente { get; set; }

    public string Nombre { get; set; }

    public decimal Precio { get; set; }

    public int Stock { get; set; }

    public int? StockMinimo { get; set; }

    public string UrlImg { get; set; }

    public virtual ICollection<DetallePedido> DetallesPedidos { get; set; } = new List<DetallePedido>();

    public virtual ICollection<EspecificacionComponente> EspecificacionesComponentes { get; set; } = new List<EspecificacionComponente>();

    public virtual Marca IdMarcaNavigation { get; set; }

    public virtual TipoComponente IdTipoComponenteNavigation { get; set; }
}