// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaPc.DLL.Models;

public partial class FormaPago
{
    public int IdFormaPago { get; set; }

    public string NombreFormaPago { get; set; }

    public decimal? Recargo { get; set; }

    public decimal? Descuento { get; set; }

    public virtual ICollection<PedidosFormasPago> PedidosFormasPagos { get; set; } = new List<PedidosFormasPago>();
}