// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaPc.DLL.Models;

public partial class Marca
{
    public int IdMarca { get; set; }

    public string NombreMarca { get; set; }

    public virtual ICollection<Componente> Componentes { get; set; } = new List<Componente>();
}