// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaPc.DLL.Models;

public partial class Pedido
{
    public int IdPedido { get; set; }

    public int IdCliente { get; set; }

    public int? IdCategoriaFiscal { get; set; }

    public int? LegajoEmp { get; set; }

    public bool ArmadoPc { get; set; }

    public decimal? PrecioArmadoPc { get; set; }

    public DateTime FechaPedido { get; set; }

    public int IdFormaEntrega { get; set; }

    public virtual ICollection<DetallePedido> DetallesPedidos { get; set; } = new List<DetallePedido>();

    public virtual CategoriaFiscal IdCategoriaFiscalNavigation { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual FormaEntrega IdFormaEntregaNavigation { get; set; }

    public virtual Empleado LegajoEmpNavigation { get; set; }

    public virtual ICollection<PedidosFormasPago> PedidosFormasPagos { get; set; } = new List<PedidosFormasPago>();
}